# Generated by Django 5.2.6 on 2025-09-07 17:48

import apps.common.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoplay_enabled', models.BooleanField(default=True)),
                ('default_volume', models.PositiveIntegerField(default=70, help_text='Default volume (0-100)')),
                ('shuffle_enabled', models.BooleanField(default=False)),
                ('repeat_mode', models.CharField(choices=[('none', 'No Repeat'), ('one', 'Repeat One'), ('all', 'Repeat All')], default='none', max_length=20)),
                ('crossfade_duration', models.PositiveIntegerField(default=0, help_text='Crossfade duration in seconds')),
            ],
            options={
                'verbose_name': 'Music Settings',
                'verbose_name_plural': 'Music Settings',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='music/playlist_covers/', validators=[apps.common.utils.validate_image_file])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='music/tracks/', validators=[apps.common.utils.validate_audio_file])),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='music/covers/', validators=[apps.common.utils.validate_image_file])),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('is_featured', models.BooleanField(default=False)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.track')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', through='music.PlaylistTrack', to='music.track'),
        ),
        migrations.CreateModel(
            name='PlayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('duration_played', models.PositiveIntegerField(default=0, help_text='Duration played in seconds')),
                ('completed', models.BooleanField(default=False, help_text='Whether the track was played to completion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to='music.track')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['is_featured', 'sort_order'], name='music_track_is_feat_9fe09f_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['uploader'], name='music_track_uploade_d72805_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together={('playlist', 'track')},
        ),
        migrations.AddIndex(
            model_name='playhistory',
            index=models.Index(fields=['user', 'played_at'], name='music_playh_user_id_976d45_idx'),
        ),
        migrations.AddIndex(
            model_name='playhistory',
            index=models.Index(fields=['track', 'played_at'], name='music_playh_track_i_937935_idx'),
        ),
        migrations.AddIndex(
            model_name='playhistory',
            index=models.Index(fields=['session_key'], name='music_playh_session_96dfa9_idx'),
        ),
    ]
